In [ ]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case)
dev = qml.device('default.qubit', wires=2)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.state()      # We calculate the final state vector in computational basis using mathematics

print(circuit_1())          

In [ ]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case)
dev = qml.device('default.qubit', wires=2)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.density_matrix(wires=range(2))      # We calculate the final state density matrix of the full system in computational basis using mathematics

print(circuit_1())          

[[0.5+0.j 0. +0.j 0. +0.j 0.5+0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0. +0.j 0. +0.j 0. +0.j 0. +0.j]
 [0.5+0.j 0. +0.j 0. +0.j 0.5+0.j]]


In [4]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case)
dev = qml.device('default.qubit', wires=2)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.density_matrix(wires=0)      # We calculate the final state density matrix of the first qubit in computational basis using mathematics

print(circuit_1())          

[[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]


In [ ]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case)
dev = qml.device('default.qubit', wires=2)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.probs(wires=range(2))      # We calculate the final probabilities in computational basis using mathematics

print(circuit_1())          

[0.5 0.  0.  0.5]


In [6]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case)
dev = qml.device('default.qubit', wires=2)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.probs(wires=0)      # We calculate the final probabilities of the first qubit in computational basis using mathematics

print(circuit_1())       

[0.5 0.5]


In [ ]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case); we have to put shots = times circuit is run. 
dev = qml.device('default.qubit', wires=2, shots = 5)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.expval(qml.PauliZ(0))   # We calculate expectation value of  pauli z operator on the first qubit in the computational basis

print(circuit_1()) 

if we have a real device we have to run the circuit several times to calculate averages for checking compatibility with theoretical predictions.
Here we can't use .state, .density_matrix; we don't have the real knoweledge of the quantum state.

In [11]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case); we have to put shots = times circuit is run. 
dev = qml.device('default.qubit', wires=2, shots = 5)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.sample()   # Measurement we can do on real hardware; we are measuring in the computational basis

print(circuit_1())       

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]]


In [12]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case); we have to put shots = times circuit is run. 
dev = qml.device('default.qubit', wires=2, shots = 5)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.counts()   # Measurement we can do on real hardware; we are measuring in the computational basis

print(circuit_1())       

{'00': 1, '11': 4}


In [14]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case); we have to put shots = times circuit is run. 
dev = qml.device('default.qubit', wires=2, shots = 120)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.probs()   # Measurement we can do on real hardware; we are measuring in the computational basis; we are obtaining experimental probabilities

print(circuit_1())       

[0.51666667 0.         0.         0.48333333]


In [19]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case); we have to put shots = times circuit is run. 
dev = qml.device('default.qubit', wires=2, shots = 5)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.expval(qml.PauliZ(0))   # Measurement we can do on real hardware; we are measuring pauli z operator on the first qubit in the computational basis

print(circuit_1())       

0.2


In [23]:
import pennylane as qml
import numpy as np

# define the qubits ( 2 in this case); we have to put shots = times circuit is run. 
dev = qml.device('default.qubit', wires=2, shots = 6)

# here we do quantum operations
@qml.qnode(dev)
def circuit_1():
    qml.Hadamard(wires=0)   # Hadamard gate on qubit 0
    qml.CNOT(wires=[0,1])   # Cnot gate on qubits 0,1

    return qml.sample(qml.PauliZ(0))  

print(circuit_1())       

[-1.  1. -1. -1. -1. -1.]
